version: '3.1'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mc_spring_cloud
    volumes:
      - ./mysql_data:/var/lib/mysql
volumes:
  mysql_data:
    driver: local